"use client";

import { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "es" | "en";

const en: Record<string, string> = {
  "Sobre nosotros": "About us", "Operaciones": "Operations", "Vuelos en vivo": "Live flights", "Únete": "Join us", "Privacidad": "Privacy", "Términos de uso": "Terms of use",
  "Simulación realista, operaciones online y comunidad.": "Realistic simulation, online operations and community.", "Todos los derechos reservados.": "All rights reserved.", "Proyecto de aviación virtual. No afiliado a ninguna aerolínea real.": "Virtual aviation project. Not affiliated with any real airline.",
  "Abrir navegación": "Open navigation", "HISPAFLY inicio": "HISPAFLY home",
  "Vuela desde España.": "Fly from Spain.", "Opera como una aerolínea.": "Operate like an airline.", "Únete a Discord": "Join Discord", "Conoce más sobre nosotros": "Learn more about us", "Una forma más realista de volar.": "A more realistic way to fly.",
  "HISPAFLY es una aerolínea virtual creada para pilotos que buscan una experiencia más realista, organizada y cercana a la operación de una aerolínea moderna.": "HISPAFLY is a virtual airline created for pilots looking for a more realistic, organized experience closer to modern airline operations.",
  "Volamos en VATSIM, planificamos con SimBrief y conectamos cada operación con nuestras propias herramientas.": "We fly on VATSIM, plan with SimBrief and connect every operation with our own tools.",
  "La base de nuestra operación virtual.": "The foundation of our virtual operation.", "Primer paso": "First step", "Listo para volar con nosotros?": "Ready to fly with us?", "¿Listo para volar con nosotros?": "Ready to fly with us?", "Conoce HISPAFLY": "Discover HISPAFLY",
  "Forma parte de una comunidad que combina simulación realista, operaciones en VATSIM y herramientas propias para pilotos.": "Join a community combining realistic simulation, VATSIM operations and purpose-built pilot tools.", "Acceso reservado al entorno operativo HISPAFLY AOC.": "Reserved access to the HISPAFLY AOC operational environment.",
  "Nacimos para volar de una forma más realista.": "Born to fly in a more realistic way.", "Nuestra historia": "Our story", "Comunidad, tecnología y realismo operacional.": "Community, technology and operational realism.", "Nuestra visión": "Our vision", "Nuestra forma de operar": "How we operate", "Comunidad": "Community", "Tecnología operativa": "Operational technology", "Nuestro ecosistema": "Our ecosystem", "Las piezas que conectan nuestra operación.": "The pieces that connect our operation.", "Forma parte de HISPAFLY": "Become part of HISPAFLY",
  "Una operación con contexto, preparación y continuidad.": "An operation with context, preparation and continuity.", "Herramientas y procedimientos dentro de un mismo ecosistema.": "Tools and procedures within one ecosystem.", "Pilotos que dan vida a la aerolínea.": "Pilots who bring the airline to life.", "EFB, ACARS y AOC para conectar cada fase del vuelo.": "EFB, ACARS and AOC connecting every phase of flight.",
  "Tu próximo vuelo empieza aquí": "Your next flight starts here", "Requisitos": "Requirements", "Todo lo que necesitas para empezar": "Everything you need to get started", "Proceso de incorporación": "Joining process", "Entra en Discord": "Join Discord", "Regístrate en vAMSYS": "Register with vAMSYS", "Realiza tu primer vuelo": "Complete your first flight", "Ir a vAMSYS": "Go to vAMSYS",
  "Interés genuino por la aviación y el aprendizaje": "A genuine interest in aviation and learning", "Actitud respetuosa y colaborativa": "A respectful, collaborative attitude", "Simulador de vuelo compatible": "A compatible flight simulator", "Cuenta activa en vAMSYS": "An active vAMSYS account", "Compromiso con las normas de la comunidad": "Commitment to the community rules",
  "Realismo desde la planificación hasta el shutdown": "Realism from planning to shutdown", "Cómo operamos": "How we operate", "Un flujo de trabajo diseñado para pilotos": "A workflow designed for pilots", "Red de rutas": "Route network", "OFP y Dispatch": "OFP and Dispatch", "Soporte operativo": "Operational support", "Seguimiento": "Tracking", "Selecciona y prepara tu vuelo": "Select and prepare your flight", "Opera con procedimientos consistentes": "Operate with consistent procedures", "Registra y revisa la operación": "Log and review the operation",
  "La información correcta, en el momento correcto": "The right information, at the right time", "Tu espacio de trabajo operativo": "Your operational workspace", "Documentación": "Documentation", "Meteorología": "Weather", "Diseño responsive": "Responsive design", "Separación clara": "Clear separation", "EFB para el piloto. AOC para la operación.": "EFB for the pilot. AOC for operations.",
  "El centro de nuestra operación": "The center of our operation", "Información operativa en un solo lugar": "Operational information in one place", "Un sistema separado": "A separate system", "Acceso seguro": "Secure access", "Accede al sistema AOC": "Access the AOC system", "Continúa en la plataforma operacional independiente.": "Continue to the independent operational platform.",
  "Nuestra flota": "Our fleet", "El avion adecuado para cada mision": "The right aircraft for every mission", "Flota HISPAFLY": "HISPAFLY fleet", "Datos sincronizados desde HISPAFLY AOC": "Data synchronized from HISPAFLY AOC", "Vista publica de referencia": "Public reference view", "Cargando flota publicada...": "Loading published fleet...", "Aircraft portfolio": "Aircraft portfolio", "Seats": "Seats", "Cargo": "Cargo", "Corto y medio radio": "Short and medium haul", "Largo radio": "Long haul",
  "Aircraft Location": "Aircraft location", "Cargando ubicación de la flota...": "Loading fleet location...", "No se pudo cargar la ubicación de la flota.": "Fleet location could not be loaded.", "No hay datos públicos de ubicación disponibles en este momento.": "No public location data is available at this time.", "Aeropuerto": "Airport", "Última ruta": "Last route", "Actualizado": "Updated", "Disponible": "Available", "En vuelo": "In flight", "Programado para próxima operación": "Scheduled for the next operation", "Ubicación pendiente de actualizar": "Location pending update",
  "Operación en tiempo real": "Real-time operations", "Conectando con AOC…": "Connecting to AOC…", "Vuelo": "Flight", "Ruta": "Route", "Aeronave": "Aircraft", "Fase": "Phase", "Altitud / GS": "Altitude / GS", "Estado": "Status", "No hay vuelos ACARS activos en este momento.": "There are no active ACARS flights at this time.",
  "Política de privacidad": "Privacy policy", "Última actualización: julio de 2026": "Last updated: July 2026", "Condiciones aplicables al uso de la web y los servicios de la comunidad HISPAFLY.": "Terms applicable to the use of the website and HISPAFLY community services.",
  "1. Naturaleza del proyecto": "1. Nature of the project", "2. Uso del sitio": "2. Use of the site", "3. Servicios externos": "3. External services", "4. Propiedad intelectual": "4. Intellectual property", "5. Disponibilidad": "5. Availability", "6. Conducta": "6. Conduct",
  "1. Responsable": "1. Data controller", "2. Datos tratados": "2. Data processed", "3. Finalidad": "3. Purpose", "4. Enlaces externos": "4. External links", "5. Derechos": "5. Rights", "6. Actualizaciones": "6. Updates",
  "SOBRE HISPAFLY": "ABOUT HISPAFLY", "NUESTRA HISTORIA": "OUR STORY", "NUESTRA VISIÓN": "OUR VISION", "NUESTRA FORMA DE OPERAR": "HOW WE OPERATE", "TECNOLOGÍA OPERATIVA": "OPERATIONAL TECHNOLOGY", "NUESTRO ECOSISTEMA": "OUR ECOSYSTEM",
  "HISPAFLY es una aerolínea virtual creada en 2025 con una idea clara: ofrecer a los pilotos una experiencia de simulación más completa, organizada y cercana a la operación real de una compañía aérea.": "HISPAFLY is a virtual airline founded in 2025 with a clear idea: to offer pilots a more complete, organized simulation experience closer to real airline operations.",
  "Desde nuestros inicios, hemos desarrollado nuestro proyecto alrededor del entorno online de VATSIM, aprovechando la actividad, el control ATC en vivo y los procedimientos de red para dar más sentido a cada vuelo. Nuestra relación con VATSIM España refuerza esta visión, acercando nuestras operaciones al espacio aéreo español, a sus eventos y a una comunidad que comparte la misma pasión por la aviación virtual.": "From the beginning, we have built our project around the VATSIM online environment, using its activity, live ATC and network procedures to give every flight more meaning. Our relationship with VATSIM Spain reinforces this vision, bringing our operations closer to Spanish airspace, its events and a community sharing the same passion for virtual aviation.",
  "Para nosotros, volar no es únicamente completar una ruta. Cada operación empieza mucho antes del despegue: con una planificación adecuada, una preparación operativa clara y una forma de trabajar que permite al piloto sentirse parte de una estructura más amplia.": "For us, flying is more than completing a route. Every operation begins long before takeoff, with proper planning, clear operational preparation and a workflow that lets the pilot feel part of a wider structure.",
  "Por eso integramos herramientas como SimBrief en nuestro flujo de trabajo y desarrollamos nuestras propias soluciones EFB, ACARS y AOC, con el objetivo de conectar la planificación, el seguimiento de vuelos, la comunicación operativa y la gestión interna de la aerolínea.": "That is why we integrate tools such as SimBrief into our workflow and develop our own EFB, ACARS and AOC solutions to connect planning, flight tracking, operational communication and internal airline management.",
  "HISPAFLY combina comunidad, tecnología y realismo operacional para construir una experiencia diferente dentro de la aviación virtual.": "HISPAFLY combines community, technology and operational realism to create a different virtual aviation experience.",
  "Nuestro objetivo es construir una aerolínea virtual donde cada piloto pueda disfrutar de una experiencia más realista, sin perder el espíritu de comunidad que hace especial a la simulación aérea.": "Our goal is to build a virtual airline where every pilot can enjoy a more realistic experience without losing the community spirit that makes flight simulation special.",
  "Queremos que cada vuelo tenga contexto, preparación y continuidad. Que las rutas, la flota, las herramientas y las comunicaciones formen parte de una operación coherente.": "We want every flight to have context, preparation and continuity, with routes, fleet, tools and communications forming one coherent operation.",
  "HISPAFLY nace como un proyecto de simulación, pero con una forma de trabajar inspirada en la aviación real.": "HISPAFLY began as a simulation project, with a way of working inspired by real-world aviation.",
  "Trabajamos sobre una base operativa inspirada en el funcionamiento de una aerolínea moderna. La planificación con SimBrief, las operaciones en VATSIM, el seguimiento de vuelos y el uso de herramientas propias forman parte de un mismo ecosistema.": "We work on an operational foundation inspired by a modern airline. SimBrief planning, VATSIM operations, flight tracking and our own tools all belong to the same ecosystem.",
  "Nuestro sistema AOC permite separar la web pública del entorno operativo interno, facilitando la gestión de vuelos, pilotos, flota y actividad operacional.": "Our AOC separates the public website from the internal operational environment, making it easier to manage flights, pilots, fleet and operational activity.", "No buscamos complicar la simulación. Buscamos darle más sentido.": "We do not aim to complicate simulation. We aim to give it more meaning.",
  "HISPAFLY es, ante todo, una comunidad. Reunimos a pilotos interesados en la simulación realista, las operaciones online y el aprendizaje continuo.": "Above all, HISPAFLY is a community. We bring together pilots interested in realistic simulation, online operations and continuous learning.",
  "Creemos en una aviación virtual abierta, organizada y colaborativa, donde cada miembro pueda volar, aprender, participar en eventos y formar parte del crecimiento del proyecto.": "We believe in open, organized and collaborative virtual aviation, where every member can fly, learn, join events and contribute to the project's growth.", "La tecnología nos ayuda a operar mejor, pero son los pilotos quienes dan vida a la aerolínea.": "Technology helps us operate better, but pilots bring the airline to life.",
  "Desde 2025, HISPAFLY trabaja en el desarrollo de un ecosistema operativo propio. Nuestro objetivo es conectar diferentes fases del vuelo en una misma experiencia: planificación, preparación, operación, seguimiento y reporte.": "Since 2025, HISPAFLY has been developing its own operational ecosystem. Our goal is to connect the different phases of flight in one experience: planning, preparation, operation, tracking and reporting.",
  "El desarrollo de herramientas como EFB, ACARS y AOC nos permite crear una estructura más cercana a la de una compañía aérea moderna, adaptada al mundo de la simulación.": "Developing tools such as EFB, ACARS and AOC lets us create a structure closer to a modern airline, adapted to the simulation world.", "Estas soluciones no sustituyen la experiencia del piloto: la complementan.": "These solutions do not replace the pilot experience; they complement it.",
  "Una estructura operativa clara para que cada vuelo tenga contexto, información y continuidad.": "A clear operational structure giving every flight context, information and continuity.", "El ecosistema HISPAFLY conecta programación, planificación y seguimiento sin añadir complejidad innecesaria.": "The HISPAFLY ecosystem connects scheduling, planning and tracking without unnecessary complexity.",
  "Operaciones domésticas, europeas e intercontinentales desde nuestras bases en España.": "Domestic, European and intercontinental operations from our Spanish bases.", "Información de ruta, combustible, meteorología y NOTAM organizada antes de cada salida.": "Route, fuel, weather and NOTAM information organized before every departure.", "Programación regular junto a vuelos chárter, tours y eventos de comunidad.": "Regular schedules together with charter flights, tours and community events.", "Recursos y briefing para ayudar al piloto durante toda la operación.": "Resources and briefings supporting the pilot throughout the operation.", "Registro de actividad y métricas para comprender y mejorar cada vuelo.": "Activity records and metrics to understand and improve every flight.",
  "Forma parte de una comunidad comprometida con la aviación virtual realista.": "Join a community committed to realistic virtual aviation.",
  "El EFB de HISPAFLY reúne herramientas y documentación para acompañar al piloto antes, durante y después del vuelo.": "The HISPAFLY EFB brings together tools and documentation supporting the pilot before, during and after the flight.", "Un punto de acceso claro a los recursos que necesitas para preparar y ejecutar cada vuelo.": "A clear access point to the resources needed to prepare and operate every flight.", "Acceso organizado a recursos y documentación relevante para la operación.": "Organized access to resources and documentation relevant to the operation.", "Información meteorológica presentada para apoyar la toma de decisiones.": "Weather information presented to support decision-making.", "Datos y briefing operacional de aeropuertos de nuestra red.": "Airport data and operational briefings across our network.", "Herramientas de apoyo para cálculos y preparación del vuelo.": "Supporting tools for calculations and flight preparation.", "Consulta del Operational Flight Plan y datos esenciales de la rotación.": "Access to the Operational Flight Plan and essential rotation data.", "Disponible desde ordenador, tablet o móvil durante toda la operación.": "Available on desktop, tablet or mobile throughout the operation.", "El EFB está orientado al trabajo del piloto y al acceso rápido a información de vuelo.": "The EFB is designed for pilot workflows and quick access to flight information.", "El AOC es un sistema independiente para gestión, coordinación y control operacional. Ambos productos forman parte del ecosistema HISPAFLY, pero cumplen funciones distintas.": "The AOC is an independent system for management, coordination and operational control. Both products are part of the HISPAFLY ecosystem, but serve different purposes.",
  "HISPAFLY AOC es el sistema independiente para coordinar, supervisar y gestionar la actividad operacional.": "HISPAFLY AOC is the independent system for coordinating, supervising and managing operational activity.", "El AOC conecta la planificación y el seguimiento con las personas responsables de mantener la operación en movimiento.": "The AOC connects planning and tracking with the people responsible for keeping the operation moving.", "La web oficial y el AOC operan en dominios y proyectos distintos. El acceso al sistema se realiza exclusivamente desde aoc.hispafly.es.": "The official website and AOC operate on separate domains and projects. The system is accessed exclusively through aoc.hispafly.es.", "Visibilidad de la actividad operacional y sus indicadores.": "Visibility into operational activity and its indicators.", "Programación y coordinación de recursos de vuelo.": "Scheduling and coordination of flight resources.", "Espacios de trabajo para los equipos responsables.": "Workspaces for the responsible teams.",
  "La web oficial y el AOC operan en dominios y proyectos distintos. El acceso al sistema se realiza exclusivamente desde": "The official website and AOC operate on separate domains and projects. The system is accessed exclusively through", "Con demora": "Delayed",
  "Una seleccion de aeronaves capaz de conectar nuestra red domestica, europea e intercontinental.": "A selection of aircraft capable of connecting our domestic, European and intercontinental network.", "Aeronaves publicadas desde HISPAFLY AOC para presentar la flota operativa de forma segura.": "Aircraft published from HISPAFLY AOC to present the operational fleet safely.", "Flota principal para la red domestica y europea, con alta frecuencia y operacion flexible.": "Main fleet for the domestic and European network, offering high frequency and flexible operations.", "Aeronave de fuselaje ancho para operaciones intercontinentales y rutas de gran autonomia.": "Wide-body aircraft for intercontinental operations and long-range routes.", "Plataforma de pasillo unico para operaciones de alta disponibilidad en la red europea.": "Single-aisle platform for high-availability operations across the European network.", "La informacion publica de la flota puede cambiar segun la programacion operativa. Los datos tecnicos internos, mantenimiento y costes permanecen dentro de HISPAFLY AOC.": "Public fleet information may change according to operational scheduling. Internal technical, maintenance and cost data remain within HISPAFLY AOC.", "La ubicación de la flota se actualiza a partir del sistema operativo HISPAFLY AOC.": "Fleet location is updated from the HISPAFLY AOC operational system.", "Información orientativa para simulación virtual. La disponibilidad puede variar según la programación operativa.": "Reference information for virtual simulation. Availability may vary according to operational scheduling.", "Consulta los requisitos de ingreso y empieza a operar la flota HISPAFLY.": "Check the entry requirements and start operating the HISPAFLY fleet.",
  "Únete a una comunidad española que combina operaciones realistas, tecnología y pasión por la aviación.": "Join a Spanish community combining realistic operations, technology and a passion for aviation.", "Conoce a la comunidad y revisa la información inicial.": "Meet the community and review the initial information.", "Crea tu perfil y solicita el ingreso en HISPAFLY.": "Create your profile and apply to join HISPAFLY.", "Elige una operación disponible y despega con nosotros.": "Choose an available operation and take off with us.",
  "Sigue la posición y el estado operativo de los vuelos HISPAFLY conectados mediante ACARS.": "Follow the position and operational status of HISPAFLY flights connected through ACARS.", "CON DEMORA": "DELAYED",
  "Información clara sobre el tratamiento de datos en la web oficial de HISPAFLY.": "Clear information about data processing on the official HISPAFLY website.", "HISPAFLY gestiona este sitio informativo como proyecto de aviación virtual. Para cuestiones de privacidad, utiliza nuestros canales oficiales de contacto.": "HISPAFLY operates this information website as a virtual aviation project. For privacy matters, use our official contact channels.", "La web pública no solicita datos personales mediante formularios. Los servicios externos enlazados, como Discord y vAMSYS, aplican sus propias políticas de privacidad.": "The public website does not request personal data through forms. Linked external services such as Discord and vAMSYS apply their own privacy policies.", "Los datos técnicos estrictamente necesarios se emplean para ofrecer, proteger y mejorar el funcionamiento del sitio web.": "Strictly necessary technical data is used to provide, protect and improve the website.", "Al abandonar este sitio, el tratamiento de datos pasa a depender del proveedor del servicio de destino. Recomendamos consultar sus condiciones antes de registrarte.": "When leaving this site, data processing becomes the responsibility of the destination service provider. We recommend reviewing its terms before registering.", "Puedes solicitar información, rectificación o supresión de datos que HISPAFLY pudiera conservar contactando con el equipo responsable.": "You may request information, correction or deletion of data HISPAFLY may retain by contacting the responsible team.", "Esta política podrá actualizarse para reflejar cambios técnicos, legales u operativos. La versión vigente siempre estará publicada en esta página.": "This policy may be updated to reflect technical, legal or operational changes. The current version will always be published on this page.",
  "HISPAFLY es un proyecto de aviación virtual sin relación con una compañía aérea real. No comercializa vuelos, billetes ni servicios de transporte.": "HISPAFLY is a virtual aviation project unrelated to any real airline. It does not sell flights, tickets or transport services.", "El contenido se ofrece con fines informativos y de comunidad. No debe utilizarse para operaciones aeronáuticas reales ni como fuente oficial de navegación.": "Content is provided for information and community purposes. It must not be used for real aviation operations or as an official navigation source.", "Discord, vAMSYS, VATSIM y otros servicios enlazados son plataformas independientes y están sujetos a sus propios términos.": "Discord, vAMSYS, VATSIM and other linked services are independent platforms subject to their own terms.", "La identidad visual, los contenidos originales y las interfaces propias de HISPAFLY están protegidos. Las marcas y recursos de terceros pertenecen a sus respectivos titulares y conservan sus licencias aplicables.": "HISPAFLY's visual identity, original content and proprietary interfaces are protected. Third-party brands and resources belong to their respective owners and retain their applicable licenses.", "Podemos modificar, suspender o retirar funciones y contenidos para mantenimiento, seguridad o evolución del proyecto.": "We may modify, suspend or remove features and content for maintenance, security or project development.", "La participación en la comunidad requiere respeto, colaboración y cumplimiento de las normas publicadas en nuestros canales oficiales.": "Community participation requires respect, collaboration and compliance with the rules published through our official channels.",
  "El entorno online donde nuestras operaciones cobran vida, con tráfico real, control ATC en vivo y procedimientos operativos.": "The online environment where our operations come to life, with real traffic, live ATC and operational procedures.", "Una comunidad clave para nuestras operaciones en el espacio aéreo español, eventos y colaboración dentro de la aviación virtual.": "A key community for our operations in Spanish airspace, events and collaboration within virtual aviation.", "Herramienta esencial para la planificación de vuelos, preparación de OFP, rutas, combustible y datos operativos.": "An essential tool for flight planning, OFP preparation, routes, fuel and operational data.", "Nuestro entorno interno para la gestión operativa, seguimiento de vuelos, pilotos, flota y actividad de la aerolínea.": "Our internal environment for operational management, flight tracking, pilots, fleet and airline activity.", "Herramientas diseñadas para conectar al piloto con la operación antes, durante y después del vuelo.": "Tools designed to connect the pilot with operations before, during and after the flight.", "Si buscas una aerolínea virtual con operaciones más realistas, herramientas modernas y una comunidad activa, HISPAFLY es tu lugar.": "If you are looking for a virtual airline with more realistic operations, modern tools and an active community, HISPAFLY is your place.", "Únete a nosotros y empieza a vivir la simulación aérea desde una perspectiva más operativa.": "Join us and start experiencing flight simulation from a more operational perspective.", "HISPAFLY es un proyecto de aviación virtual y simulación aérea. No está afiliado a ninguna aerolínea real ni representa una operación comercial real.": "HISPAFLY is a virtual aviation and flight simulation project. It is not affiliated with any real airline and does not represent a real commercial operation.",
};

const es: Record<string, string> = {
  "Home": "Inicio", "About": "Nosotros", "Operations": "Operaciones", "Ecosystem": "Ecosistema", "Live flights": "Vuelos en vivo", "Join Us": "Únete", "Join us": "Únete", "Access AOC": "Acceder al AOC",
  "HISPAFLY Official Website": "Sitio web oficial de HISPAFLY", "Operational Network": "Red operacional", "Community Collaboration": "Colaboración con la comunidad", "Flight Planning Integration": "Integración de planificación de vuelo", "Operational Ecosystem": "Ecosistema operacional",
  "MORE THAN A VIRTUAL AIRLINE.\nA COMPLETE VIRTUAL AIRLINE ECOSYSTEM.": "MÁS QUE UNA AEROLÍNEA VIRTUAL.\nUN ECOSISTEMA AÉREO VIRTUAL COMPLETO.", "More than a virtual airline.": "Más que una aerolínea virtual.", "A complete virtual airline ecosystem.": "Un ecosistema aéreo virtual completo.", "Explore the ecosystem": "Explorar el ecosistema", "See live operations": "Ver operaciones en vivo",
  "ONE CONNECTED OPERATION": "UNA OPERACIÓN CONECTADA", "Four systems.\nOne airline.": "Cuatro sistemas.\nUna aerolínea.", "Four systems.": "Cuatro sistemas.", "One airline.": "Una aerolínea.", "Everything Connected": "Todo conectado", "EVERYTHING CONNECTED": "TODO CONECTADO",
  "THE PUBLIC FACE": "LA CARA PÚBLICA", "Discover. Plan. Fly.": "Descubre. Planifica. Vuela.", "THE OPERATIONAL HEART": "EL CORAZÓN OPERACIONAL", "The airline, under control.": "La aerolínea, bajo control.", "IN THE COCKPIT": "EN LA CABINA", "The right data. At the right time.": "Los datos correctos. En el momento adecuado.", "GATE TO GATE": "DE PUERTA A PUERTA", "Every flight stays connected.": "Cada vuelo permanece conectado.",
  "Fleet": "Flota", "Live Operations": "Operaciones en vivo", "Pilot Portal": "Portal del piloto", "Dispatch": "Despacho", "Scheduling": "Programación", "Operational Control": "Control operacional", "Briefing": "Briefing", "Weather & PDC": "Meteorología y PDC", "AOC Integration": "Integración AOC", "Live Tracking": "Seguimiento en vivo", "Flight Data": "Datos de vuelo",
  "REAL HISPAFLY INTERFACE": "INTERFAZ REAL DE HISPAFLY", "Official website": "Web oficial", "Connected fleet portfolio": "Flota conectada", "Flight operations": "Operaciones de vuelo", "Operations dashboard": "Panel de operaciones", "Airport scheduling": "Programación aeroportuaria", "Pilot self-dispatch": "Autodespacho del piloto", "Flight marketplace": "Mercado de vuelos", "PIREP management": "Gestión de PIREP", "Operational flight analysis": "Análisis operacional del vuelo", "Weekly operations planning": "Planificación semanal", "Flight Center & dispatch": "Centro de vuelos y despacho", "Operational weather": "Meteorología operacional", "Airport CDM status": "Estado CDM del aeropuerto", "Secure AOC connection": "Conexión segura con AOC",
  "PILOT EXPERIENCE": "EXPERIENCIA DEL PILOTO", "OPERATIONS CENTER": "CENTRO DE OPERACIONES", "PUBLIC EXPERIENCE": "EXPERIENCIA PÚBLICA", "One airline. One operational platform. One connected experience.": "Una aerolínea. Una plataforma operacional. Una experiencia conectada.", "BUILT BY HISPAFLY · DESIGNED FOR HISPAFLY OPERATIONS": "CREADO POR HISPAFLY · DISEÑADO PARA LAS OPERACIONES HISPAFLY",
  "From flight planning to cockpit operations, ACARS tracking and airline management — everything works together inside HISPAFLY.": "Desde la planificación del vuelo hasta las operaciones en cabina, el seguimiento ACARS y la gestión de la aerolínea: todo funciona conectado dentro de HISPAFLY.", "Each HISPAFLY platform has a clear role. Together they create one continuous operational experience — from the public website to the flight deck and back to Operations Control.": "Cada plataforma HISPAFLY cumple una función clara. Juntas crean una experiencia operacional continua, desde la web pública hasta la cabina y de vuelta al Control de Operaciones.", "The public gateway to our airline: fleet, destinations, live operations and the pilot community — connected directly to operational data.": "La puerta pública de nuestra aerolínea: flota, destinos, operaciones en vivo y comunidad de pilotos, conectadas directamente con los datos operacionales.", "Our central operations platform brings flight planning, dispatch, fleet, crew and live monitoring into one coordinated workspace.": "Nuestra plataforma central reúne planificación, despacho, flota, tripulaciones y seguimiento en vivo en un único espacio de trabajo coordinado.", "A purpose-built pilot workspace for briefing, weather, operational documents, PDC and direct communication with the AOC.": "Un espacio creado para el piloto con briefing, meteorología, documentación operacional, PDC y comunicación directa con el AOC.", "From OUT to IN, ACARS links the simulator with Operations Control, delivering flight phase, position and aircraft data in real time.": "Desde OUT hasta IN, ACARS conecta el simulador con Control de Operaciones y transmite en tiempo real la fase de vuelo, posición y datos de la aeronave.", "Electronic Flight Bag": "Maletín electrónico de vuelo",
  "Close enlarged image": "Cerrar imagen ampliada", "Previous enlarged image": "Imagen ampliada anterior", "Next enlarged image": "Imagen ampliada siguiente", "Enlarge image": "Ampliar imagen",
};

const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void }>({ language: "es", setLanguage: () => undefined });
const originals = new WeakMap<Node, string>();
const applied = new WeakMap<Node, string>();
let originalTitle = "";
let appliedTitle = "";

function translated(original: string, language: Language) {
  const exact = (language === "en" ? en : es)[original];
  if (exact) return exact;
  if (language === "en") {
    if (original.startsWith("Disponible en ")) return original.replace("Disponible en ", "Available at ");
    if (original.startsWith("Actualizado ")) return original.replace("Actualizado ", "Updated ");
    if (original.startsWith("Abrir ")) return original.replace("Abrir ", "Open ");
    if (original.startsWith("Mostrar ")) return original.replace("Mostrar ", "Show ");
    if (/^© \d{4} HISPAFLY\. Todos los derechos reservados\.$/.test(original)) return original.replace("Todos los derechos reservados.", "All rights reserved.");
    if (original === "HISPAFLY. Todos los derechos reservados.") return "HISPAFLY. All rights reserved.";
  }
  return original;
}

function translateDocument(language: Language) {
  document.documentElement.lang = language;
  if (!originalTitle || (document.title !== appliedTitle && document.title !== originalTitle)) originalTitle = document.title;
  const titleParts = originalTitle.split(" | ");
  appliedTitle = `${translated(titleParts[0], language)}${titleParts.length > 1 ? ` | ${titleParts.slice(1).join(" | ")}` : ""}`;
  if (document.title !== appliedTitle) document.title = appliedTitle;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    const value = node.nodeValue ?? "";
    const trimmed = value.trim();
    if (!trimmed) continue;
    const lastApplied = applied.get(node);
    if (!originals.has(node) || (lastApplied !== undefined && trimmed !== lastApplied)) originals.set(node, trimmed);
    const original = originals.get(node)!;
    const next = translated(original, language);
    applied.set(node, next);
    const leading = value.match(/^\s*/)?.[0] ?? "";
    const trailing = value.match(/\s*$/)?.[0] ?? "";
    const output = `${leading}${next}${trailing}`;
    if (node.nodeValue !== output) node.nodeValue = output;
  }
  document.querySelectorAll<HTMLElement>("[aria-label], [title], [placeholder], [alt]").forEach((element) => {
    ["aria-label", "title", "placeholder", "alt"].forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (!value) return;
      const key = `data-i18n-${attribute}`;
      const original = element.getAttribute(key) ?? value;
      if (!element.hasAttribute(key)) element.setAttribute(key, original);
      element.setAttribute(attribute, translated(original, language));
    });
  });
  document.querySelectorAll<HTMLAnchorElement>('a[href^="/"]').forEach((link) => {
    const original = link.dataset.i18nHref ?? link.getAttribute("href") ?? "/";
    if (!link.dataset.i18nHref) link.dataset.i18nHref = original;
    const url = new URL(original, window.location.origin);
    if (language === "en") url.searchParams.set("lang", "en"); else url.searchParams.delete("lang");
    link.setAttribute("href", `${url.pathname}${url.search}${url.hash}`);
  });
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
    localStorage.setItem("hispafly-language", next);
    const url = new URL(window.location.href);
    if (next === "en") url.searchParams.set("lang", "en"); else url.searchParams.delete("lang");
    window.history.replaceState({}, "", url);
  }, []);

  useEffect(() => {
    const query = new URLSearchParams(window.location.search).get("lang");
    const saved = localStorage.getItem("hispafly-language");
    setLanguageState(query === "en" || (!query && saved === "en") ? "en" : "es");
  }, []);

  useEffect(() => {
    translateDocument(language);
    const observer = new MutationObserver(() => translateDocument(language));
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [language]);

  return <LanguageContext.Provider value={{ language, setLanguage }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }
