import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, CheckCircleIcon } from "@heroicons/react/24/outline";
import { EcosystemGallery } from "@/components/ecosystem-gallery";

export const metadata: Metadata = { title: "Ecosystem", description: "Discover the connected HISPAFLY WEB, AOC, EFB and ACARS operational ecosystem." };

const products = [
  { index: "01", name: "HISPAFLY WEB", label: "THE PUBLIC FACE", title: "Discover. Plan. Fly.", text: "The public gateway to our airline: fleet, destinations, live operations and the pilot community — connected directly to operational data.", screenshots: [{ src: "/assets/ecosystem/web-home-real.png", alt: "HISPAFLY public website home page", caption: "Official website" }, { src: "/assets/ecosystem/web-fleet.png", alt: "HISPAFLY fleet page", caption: "Connected fleet portfolio" }, { src: "/assets/ecosystem/web-operations.png", alt: "HISPAFLY operations page", caption: "Flight operations" }], tags: ["Fleet", "Live Operations", "Pilot Portal"] },
  { index: "02", name: "HISPAFLY AOC", label: "THE OPERATIONAL HEART", title: "The airline, under control.", text: "Our central operations platform brings flight planning, dispatch, fleet, crew and live monitoring into one coordinated workspace.", screenshots: [{ src: "/assets/ecosystem/aoc-dashboard.png", alt: "HISPAFLY AOC operations dashboard", caption: "Operations dashboard" }, { src: "/assets/ecosystem/aoc-airport-schedule.png", alt: "HISPAFLY AOC airport schedule", caption: "Airport scheduling" }, { src: "/assets/ecosystem/aoc-self-dispatch.png", alt: "HISPAFLY AOC pilot self dispatch", caption: "Pilot self-dispatch" }, { src: "/assets/ecosystem/aoc-marketplace.png", alt: "HISPAFLY AOC flight marketplace", caption: "Flight marketplace" }, { src: "/assets/ecosystem/aoc-pireps.png", alt: "HISPAFLY AOC PIREP list", caption: "PIREP management" }, { src: "/assets/ecosystem/aoc-flight-report.png", alt: "HISPAFLY AOC flight report", caption: "Operational flight analysis" }, { src: "/assets/ecosystem/aoc-planner.png", alt: "HISPAFLY AOC weekly planner", caption: "Weekly operations planning" }], tags: ["Dispatch", "Scheduling", "Operational Control"] },
  { index: "03", name: "HISPAFLY EFB", label: "IN THE COCKPIT", title: "The right data. At the right time.", text: "A purpose-built pilot workspace for briefing, weather, operational documents, PDC and direct communication with the AOC.", screenshots: [{ src: "/assets/ecosystem/efb-flight-center.png", alt: "HISPAFLY EFB flight center", caption: "Flight Center & dispatch" }, { src: "/assets/ecosystem/efb-weather.png", alt: "HISPAFLY EFB weather information", caption: "Operational weather" }, { src: "/assets/ecosystem/efb-cdm.png", alt: "HISPAFLY EFB CDM airport status", caption: "Airport CDM status" }], tags: ["Briefing", "Weather & PDC", "AOC Integration"] },
  { index: "04", name: "HISPAFLY ACARS", label: "GATE TO GATE", title: "Every flight stays connected.", text: "From OUT to IN, ACARS links the simulator with Operations Control, delivering flight phase, position and aircraft data in real time.", screenshots: [{ src: "/assets/ecosystem/acars-login.png", alt: "HISPAFLY ACARS secure sign in", caption: "Secure AOC connection" }], tags: ["OOOI", "Live Tracking", "Flight Data"] },
];

export default function EcosystemPage() { return <main className="overflow-hidden bg-[#07111f] text-white">
  <section className="relative min-h-[92vh] pt-28"><div className="absolute inset-0"><Image src="/assets/hero.jpg" alt="HISPAFLY aircraft" fill priority className="object-cover opacity-30" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(210,35,42,.22),transparent_35%),linear-gradient(90deg,#07111f_0%,rgba(7,17,31,.94)_48%,rgba(7,17,31,.64)_100%)]" /></div><div className="route-grid absolute inset-0 opacity-30" /><div className="container-site relative flex min-h-[78vh] items-center py-20"><div className="max-w-5xl"><p className="mb-6 text-xs font-bold uppercase tracking-[.34em] text-brand-yellow">HISPAFLY DIGITAL ECOSYSTEM</p><h1 className="max-w-5xl text-5xl font-black uppercase leading-[.92] tracking-[-.055em] sm:text-7xl lg:text-[96px]">More than a virtual airline.<span className="mt-3 block text-brand-yellow">A complete virtual airline ecosystem.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/70 sm:text-xl">From flight planning to cockpit operations, ACARS tracking and airline management — everything works together inside HISPAFLY.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="#connected" className="inline-flex items-center gap-3 bg-brand-red px-6 py-4 text-sm font-bold uppercase tracking-wider">Explore the ecosystem <ArrowRightIcon className="size-4" /></Link><Link href="/live-flights" className="border border-white/30 px-6 py-4 text-sm font-bold uppercase tracking-wider">See live operations</Link></div><div className="mt-16 flex flex-wrap items-center gap-x-5 gap-y-3 text-xs font-bold uppercase tracking-[.2em] text-white/55"><span className="text-white">WEB</span><span className="text-brand-red">→</span><span className="text-white">AOC</span><span className="text-brand-red">↔</span><span className="text-white">EFB</span><span className="text-brand-red">↔</span><span className="text-white">ACARS</span><span className="text-brand-red">→</span><span className="text-white">LIVE OPS</span></div></div></div></section>
  <section id="connected" className="section-space bg-white text-brand-navy"><div className="container-site"><p className="eyebrow">ONE CONNECTED OPERATION</p><div className="grid gap-8 lg:grid-cols-[1fr_.72fr] lg:items-end"><h2 className="display">Four systems.<br />One airline.</h2><p className="text-lg leading-8 text-slate-600">Each HISPAFLY platform has a clear role. Together they create one continuous operational experience — from the public website to the flight deck and back to Operations Control.</p></div></div></section>
  <section className="bg-[#edf1f5] py-20 text-brand-navy sm:py-28"><div className="container-site space-y-24">{products.map((p, i) => <article key={p.name} className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div className={i % 2 ? "lg:order-2" : ""}><div className="mb-6 flex items-center gap-4"><span className="text-5xl font-black text-brand-red/15">{p.index}</span><div><p className="text-xs font-bold tracking-[.22em] text-brand-red">{p.label}</p><h3 className="mt-1 text-xl font-black">{p.name}</h3></div></div><h4 className="text-4xl font-black leading-tight tracking-tight sm:text-5xl">{p.title}</h4><p className="mt-6 text-lg leading-8 text-slate-600">{p.text}</p><ul className="mt-7 space-y-3">{p.tags.map(t => <li key={t} className="flex items-center gap-3 font-bold"><CheckCircleIcon className="size-5 text-brand-red" />{t}</li>)}</ul></div><div className={i % 2 ? "lg:order-1" : ""}><EcosystemGallery shots={p.screenshots} product={p.name} /></div></article>)}</div></section>
  <section className="section-space relative"><div className="route-grid absolute inset-0 opacity-40" /><div className="container-site relative text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-brand-yellow">EVERYTHING CONNECTED</p><h2 className="mx-auto mt-5 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">One airline. One operational platform. One connected experience.</h2><div className="mx-auto mt-16 grid max-w-5xl gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-7"><p className="text-xs text-white/45">PILOT EXPERIENCE</p><p className="mt-2 text-2xl font-black">EFB + ACARS</p></div><div className="rounded-2xl bg-brand-red p-8 shadow-2xl"><p className="text-xs text-white/65">OPERATIONS CENTER</p><p className="mt-2 text-3xl font-black">HISPAFLY AOC</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-7"><p className="text-xs text-white/45">PUBLIC EXPERIENCE</p><p className="mt-2 text-2xl font-black">WEB + LIVE OPS</p></div></div><div className="mx-auto mt-4 h-16 w-px bg-gradient-to-b from-brand-red to-brand-yellow" /><p className="text-sm font-bold uppercase tracking-[.28em] text-white/60">BUILT BY HISPAFLY · DESIGNED FOR HISPAFLY OPERATIONS</p></div></section>
</main>; }
