import type { Metadata } from "next";
import { DocumentMagnifyingGlassIcon, CloudIcon, MapIcon, CalculatorIcon, ClipboardDocumentCheckIcon, DeviceTabletIcon } from "@heroicons/react/24/outline";
import { PageHeader } from "@/components/page-header";
import { SectionTitle } from "@/components/section-title";
import { FeatureCard } from "@/components/feature-card";
import { CTASection } from "@/components/cta-section";
export const metadata: Metadata = { title: "EFB" };
const tools = [{icon:DocumentMagnifyingGlassIcon,title:"Documentación",text:"Acceso organizado a recursos y documentación relevante para la operación."},{icon:CloudIcon,title:"Meteorología",text:"Información meteorológica presentada para apoyar la toma de decisiones."},{icon:MapIcon,title:"Airport Briefing",text:"Datos y briefing operacional de aeropuertos de nuestra red."},{icon:CalculatorIcon,title:"Performance",text:"Herramientas de apoyo para cálculos y preparación del vuelo."},{icon:ClipboardDocumentCheckIcon,title:"OFP",text:"Consulta del Operational Flight Plan y datos esenciales de la rotación."},{icon:DeviceTabletIcon,title:"Diseño responsive",text:"Disponible desde ordenador, tablet o móvil durante toda la operación."}];
export default function Efb() { return <><PageHeader eyebrow="Electronic Flight Bag" title="La información correcta, en el momento correcto" description="El EFB de HISPAFLY reúne herramientas y documentación para acompañar al piloto antes, durante y después del vuelo." image="/assets/bergen.jpg" /><section className="section-space bg-brand-navy"><div className="container-site"><SectionTitle eyebrow="Pilot workspace" title="Tu espacio de trabajo operativo" description="Un punto de acceso claro a los recursos que necesitas para preparar y ejecutar cada vuelo." light /><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{tools.map((tool) => <FeatureCard key={tool.title} {...tool} dark />)}</div></div></section><section className="section-space"><div className="container-site grid gap-10 lg:grid-cols-2"><SectionTitle eyebrow="Separación clara" title="EFB para el piloto. AOC para la operación." /><div className="space-y-5 text-lg leading-8 text-gray-600"><p>El EFB está orientado al trabajo del piloto y al acceso rápido a información de vuelo.</p><p>El AOC es un sistema independiente para gestión, coordinación y control operacional. Ambos productos forman parte del ecosistema HISPAFLY, pero cumplen funciones distintas.</p></div></div></section><CTASection /></>; }
