import type { Metadata } from "next";
import { MapIcon, DocumentTextIcon, RadioIcon, CalendarDaysIcon, CloudIcon, ChartPieIcon } from "@heroicons/react/24/outline";
import { PageHeader } from "@/components/page-header";
import { SectionTitle } from "@/components/section-title";
import { FeatureCard } from "@/components/feature-card";
import { CTASection } from "@/components/cta-section";
export const metadata: Metadata = { title: "Operations" };
const features = [{icon:MapIcon,title:"Red de rutas",text:"Operaciones domésticas, europeas e intercontinentales desde nuestras bases en España."},{icon:DocumentTextIcon,title:"OFP y Dispatch",text:"Información de ruta, combustible, meteorología y NOTAM organizada antes de cada salida."},{icon:RadioIcon,title:"VATSIM",text:"Fomentamos operaciones online coordinadas y comunicaciones profesionales."},{icon:CalendarDaysIcon,title:"Flight Offers",text:"Programación regular junto a vuelos chárter, tours y eventos de comunidad."},{icon:CloudIcon,title:"Soporte operativo",text:"Recursos y briefing para ayudar al piloto durante toda la operación."},{icon:ChartPieIcon,title:"Seguimiento",text:"Registro de actividad y métricas para comprender y mejorar cada vuelo."}];
export default function Operations() { return <><PageHeader eyebrow="Flight Operations" title="Realismo desde la planificación hasta el shutdown" description="Una estructura operativa clara para que cada vuelo tenga contexto, información y continuidad." image="/assets/shanghai.jpg" /><section className="section-space"><div className="container-site"><SectionTitle eyebrow="Cómo operamos" title="Un flujo de trabajo diseñado para pilotos" description="El ecosistema HISPAFLY conecta programación, planificación y seguimiento sin añadir complejidad innecesaria." /><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{features.map((feature) => <FeatureCard key={feature.title} {...feature} />)}</div></div></section><section className="bg-brand-navy py-16 text-white"><div className="container-site grid gap-8 text-center sm:grid-cols-3"><div><strong className="text-4xl text-brand-yellow">Plan</strong><p className="mt-2 text-white/60">Selecciona y prepara tu vuelo</p></div><div><strong className="text-4xl text-brand-yellow">Fly</strong><p className="mt-2 text-white/60">Opera con procedimientos consistentes</p></div><div><strong className="text-4xl text-brand-yellow">Review</strong><p className="mt-2 text-white/60">Registra y revisa la operación</p></div></div></section><CTASection /></>; }
